import { after, describe, test } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

import pool from "../../../config/database.js";
import { persistOrcidScan } from "../../../modules/author/repositories/orcidScan.repository.js";

describe("ORCID scan persistence", () => {
  after(async () => {
    await pool.end();
  });

  test("migration preserves the existing Article-Issue-Volume-Journal model", () => {
    const migration = readFileSync(
      new URL(
        "../../../../deploy/sql/0004_add_orcid_scan_journal_identity.sql",
        import.meta.url,
      ),
      "utf8",
    );
    assert.doesNotMatch(migration, /ALTER TABLE "Article"/);
    assert.doesNotMatch(migration, /Article_journal_id/);
    assert.match(migration, /uq_journal_normalized_source_id/);
    assert.match(migration, /CREATE TABLE IF NOT EXISTS "Journal_ISSN"/);
    assert.match(migration, /uq_volume_journal_number/);
    assert.match(migration, /uq_issue_volume_normalized_number/);
    assert.match(
      migration,
      /regexp_replace\(upper\(trim\(token\)\), '\[\^0-9X\]'/,
    );
    assert.doesNotMatch(
      migration,
      /upper\(regexp_replace\(trim\(token\), '\[\^0-9X\]'/,
    );
  });

  test.skip("progressive scan item migration uses an indexed durable cursor", () => {
    const migration = readFileSync(
      new URL(
        "../../../../deploy/sql/0006_create_orcid_scan_job_items.sql",
        import.meta.url,
      ),
      "utf8",
    );
    assert.match(
      migration,
      /item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY/,
    );
    assert.match(
      migration,
      /UNIQUE \(job_id, article_id\)/,
    );
    assert.match(
      migration,
      /ON public\."Orcid_Scan_Job_Item" \(job_id, item_id\)/,
    );
    assert.match(migration, /ENABLE ROW LEVEL SECURITY/);
    assert.match(migration, /REVOKE ALL ON TABLE/);
  });

  test("rolls back one bad article to its savepoint and commits the rest", async () => {
    const commands = [];
    let targetAuthor = null;
    let articleInsertCount = 0;

    const client = {
      query: async (sql, values = []) => {
        if (typeof sql === "object") {
          values = sql.values || [];
          sql = sql.text;
        }
        const compact = sql.replace(/\s+/g, " ").trim();
        commands.push(compact);

        if (compact.startsWith("SELECT pg_advisory_xact_lock")) {
          return { rows: [] };
        }
        if (
          compact.includes('FROM "Author"') &&
          compact.includes("FOR UPDATE")
        ) {
          return { rows: targetAuthor ? [targetAuthor] : [] };
        }
        if (compact.startsWith('INSERT INTO "Author"')) {
          targetAuthor = {
            author_id: "1",
            display_name: values[0],
            orcid: values[1],
            openalex_id: values[2],
            is_deleted: false,
          };
          return { rows: [targetAuthor] };
        }
        if (
          compact.includes('FROM "Article" a') &&
          compact.includes("FOR UPDATE OF a")
        ) {
          return { rows: [] };
        }
        if (compact.startsWith("WITH author_input AS")) {
          const authors = JSON.parse(values[0]);
          return {
            rows: authors.map((author) => ({
              identity_key: author.identity_key,
              author_id: "1",
              is_deleted: false,
            })),
          };
        }
        if (compact.startsWith("WITH matched_input AS")) {
          return { rows: [{ updated: 1, inserted: 0 }] };
        }
        if (compact.startsWith("WITH institution_input AS MATERIALIZED")) {
          const institutions = JSON.parse(values[0]);
          return {
            rows: institutions.map((institution) => ({
              identity_key: institution.identity_key,
              institution_id: "70",
            })),
          };
        }
        if (compact.startsWith("WITH article_updated AS")) {
          articleInsertCount += 1;
          if (articleInsertCount === 1) {
            throw new Error("bad article metadata");
          }
          return {
            rows: [
              {
                article_id: "20",
                created: true,
                primary_topic: null,
                topics_linked: 0,
                keywords_linked: 0,
                institutions_linked: 1,
              },
            ],
          };
        }
        if (compact.startsWith("WITH linked_articles AS MATERIALIZED")) {
          return {
            rows: [
              {
                article_id: "20",
                title: "Good article",
                total_count: 1,
              },
            ],
          };
        }
        if (
          compact.startsWith('SELECT * FROM "Author" WHERE author_id')
        ) {
          return { rows: [targetAuthor] };
        }
        return { rows: [] };
      },
      release: () => {
        commands.push("RELEASE_CLIENT");
      },
    };
    const databasePool = { connect: async () => client };

    const result = await persistOrcidScan(
      {
        targetAuthor: {
          display_name: "Target author",
          orcid: "https://orcid.org/0000-0002-1825-0097",
          institutions: [
            {
              openalex_id: "https://openalex.org/I70",
              display_name: "Fallback Institution",
            },
          ],
        },
        articles: [
          {
            title: "Bad article",
            publication_year: 2024,
            doi: "10.1000/bad",
            authors: [],
            topics: [],
            keywords: [],
          },
          {
            title: "Good article",
            publication_year: 2025,
            doi: "10.1000/good",
            authors: [],
            topics: [],
            keywords: [],
          },
        ],
      },
      { databasePool },
    );

    assert.equal(result.summary.failed_to_persist, 1);
    assert.equal(result.summary.created, 1);
    assert.equal(result.articles.length, 1);
    assert.ok(
      commands.some((command) =>
        command.startsWith("ROLLBACK TO SAVEPOINT orcid_article_0"),
      ),
    );
    assert.ok(
      commands.some((command) =>
        command.startsWith("ROLLBACK TO SAVEPOINT orcid_chunk_0"),
      ),
      "a failed bulk chunk must roll back before per-item fallback",
    );
    assert.ok(commands.includes("COMMIT"));
    assert.ok(
      commands.some(
        (command) =>
          command.startsWith("WITH article_updated AS") &&
          command.includes('INSERT INTO "Institution_Author"'),
      ),
      "individual fallback must persist Institution_Author links",
    );
    assert.equal(commands.at(-1), "RELEASE_CLIENT");
  });

  test("keeps existing metadata and fills only null article fields", async () => {
    const commands = [];
    let volumeOrIssueQueries = 0;
    const existingAuthor = {
      author_id: "1",
      display_name: "Curated author",
      orcid: "https://orcid.org/0000-0002-1825-0097",
      openalex_id: null,
      is_deleted: false,
    };
    const existingArticle = {
      article_id: "20",
      title: "Curated title",
      publication_year: 2020,
      doi: "10.1000/existing",
      citation_count: 4,
      pdf_url: null,
      is_deleted: false,
    };

    const client = {
      query: async (sql, values = []) => {
        if (typeof sql === "object") {
          values = sql.values || [];
          sql = sql.text;
        }
        const compact = sql.replace(/\s+/g, " ").trim();
        commands.push({ sql: compact, values });

        if (compact.startsWith("SELECT pg_advisory_xact_lock")) {
          return { rows: [] };
        }
        if (
          compact.includes('FROM "Author"') &&
          compact.includes("FOR UPDATE")
        ) {
          return { rows: [existingAuthor] };
        }
        if (compact.startsWith('UPDATE "Author"')) {
          return { rows: [existingAuthor] };
        }
        if (
          compact.includes('FROM "Article" a') &&
          compact.includes("FOR UPDATE OF a")
        ) {
          return { rows: [existingArticle] };
        }
        if (compact.startsWith("WITH author_input AS")) {
          const authors = JSON.parse(values[0]);
          return {
            rows: authors.map((author) => ({
              identity_key: author.identity_key,
              author_id: "1",
              is_deleted: false,
            })),
          };
        }
        if (compact.startsWith("WITH matched_input AS")) {
          return { rows: [{ updated: 1, inserted: 0 }] };
        }
        if (compact.startsWith("WITH institution_input AS MATERIALIZED")) {
          const institutions = JSON.parse(values[0]);
          return {
            rows: institutions.map((institution) => ({
              identity_key: institution.identity_key,
              institution_id: "71",
            })),
          };
        }
        if (compact.startsWith("WITH journal_input AS MATERIALIZED")) {
          const journals = JSON.parse(values[0]);
          if (compact.includes("journal_updated AS")) {
            return {
              rows: [{ updated: 1, inserted: 0, issns_linked: 1 }],
            };
          }
          return {
            rows: journals.map((journal) => ({
              identity_key: journal.identity_key,
              journal_id: "40",
            })),
          };
        }
        if (
          compact.startsWith("WITH volume_input AS MATERIALIZED") ||
          compact.startsWith("WITH issue_input AS MATERIALIZED")
        ) {
          volumeOrIssueQueries += 1;
          return { rows: [] };
        }
        if (compact.startsWith("WITH article_updated AS")) {
          return {
            rows: [
              {
                article_id: existingArticle.article_id,
                created: false,
                primary_topic: null,
                topics_linked: 0,
                keywords_linked: 0,
                institutions_linked: 1,
              },
            ],
          };
        }
        if (compact.startsWith("WITH linked_articles AS MATERIALIZED")) {
          return {
            rows: [
              {
                ...existingArticle,
                total_count: 1,
              },
            ],
          };
        }
        if (
          compact.startsWith('SELECT * FROM "Author" WHERE author_id')
        ) {
          return { rows: [existingAuthor] };
        }
        return { rows: [] };
      },
      release: () => {},
    };

    const result = await persistOrcidScan(
      {
        targetAuthor: {
          display_name: "External author",
          orcid: existingAuthor.orcid,
        },
        articles: [
          {
            title: "External title",
            publication_year: 2025,
            doi: existingArticle.doi,
            citation_count: 99,
            pdf_url: null,
            authors: [{
              orcid: existingAuthor.orcid,
              institutions: [{
                openalex_id: "I71",
                display_name: "New Rescan Institution",
              }],
            }],
            topics: [],
            keywords: [],
            journal: {
              source_id: "https://openalex.org/S40",
              display_name: "Journal without issue metadata",
              issns: ["1234-567X"],
            },
            volume_number: "Volume 12",
            issue_number: "S1",
          },
        ],
      },
      { databasePool: { connect: async () => client } },
    );

    const articleUpdate = commands.find((command) =>
      command.sql.startsWith("WITH article_updated AS"),
    );
    assert.match(
      articleUpdate.sql,
      /pdf_url = COALESCE\(article\.pdf_url, \$9\)/,
    );
    assert.doesNotMatch(
      articleUpdate.sql,
      /title = COALESCE\(article\.title/,
    );
    assert.match(
      articleUpdate.sql,
      /article_existing AS/,
      "an unchanged Article row must bypass the UPDATE write",
    );
    assert.match(
      articleUpdate.sql,
      /article\.pdf_url IS NULL AND \$9 IS NOT NULL/,
    );
    assert.equal(result.summary.created, 0);
    assert.equal(result.summary.filled_missing, 1);
    assert.equal(result.articles[0].title, "Curated title");
    assert.equal(result.article_total, 1);
    assert.equal(
      volumeOrIssueQueries,
      0,
      "journal may be upserted but no Volume/Issue may be fabricated",
    );
  });

  test("persists 100 articles in four unnamed chunks and returns the author's DB page", async () => {
    let queryCount = 0;
    let targetAuthor = null;
    let authorBatchQueries = 0;
    let topicBatchQueries = 0;
    let keywordBatchQueries = 0;
    let journalBatchQueries = 0;
    let volumeBatchQueries = 0;
    let issueBatchQueries = 0;
    let institutionBatchQueries = 0;
    let namedArticleQueries = 0;
    const perArticleSql = [];
    const bulkArticleSql = [];
    const hierarchySql = [];
    const persistedIssueIds = [];
    const resolvedIssueNumbers = [];
    const persistedInstitutionIds = [];
    let authorPageSql = null;
    const authorBatchSql = [];
    const storedArticles = Array.from({ length: 120 }, (_, index) => ({
      article_id: String(index + 1),
      title: `Article ${index}`,
      journal_id: "4000",
      journal_name: "Shared Journal",
      journal_issn: "1234567X",
    }));

    const client = {
      query: async (sql, values = []) => {
        if (typeof sql === "object") {
          if (sql.name) namedArticleQueries += 1;
          values = sql.values || [];
          sql = sql.text;
        }
        queryCount += 1;
        const compact = sql.replace(/\s+/g, " ").trim();

        if (
          compact.includes('FROM "Author"') &&
          compact.includes("FOR UPDATE")
        ) {
          return { rows: targetAuthor ? [targetAuthor] : [] };
        }
        if (compact.startsWith('INSERT INTO "Author"')) {
          targetAuthor = {
            author_id: "1000",
            display_name: values[0],
            orcid: values[1],
            openalex_id: values[2],
            is_deleted: false,
          };
          return { rows: [targetAuthor] };
        }
        if (
          compact.includes('FROM "Article" a') &&
          compact.includes("FOR UPDATE OF a")
        ) {
          return { rows: [] };
        }
        if (compact.startsWith("WITH author_input AS")) {
          authorBatchQueries += 1;
          authorBatchSql.push(compact);
          const authors = JSON.parse(values[0]);
          return {
            rows: authors.map((author) => ({
              identity_key: author.identity_key,
              author_id: "1000",
              is_deleted: false,
            })),
          };
        }
        if (compact.startsWith("WITH matched_input AS")) {
          authorBatchQueries += 1;
          authorBatchSql.push(compact);
          return { rows: [{ updated: 1, inserted: 0 }] };
        }
        if (compact.startsWith("WITH topic_input AS")) {
          topicBatchQueries += 1;
          const topics = JSON.parse(values[0]);
          return {
            rows: topics.map((topic, index) => ({
              identity_key: topic.identity_key,
              topic_id: String(index + 2000),
            })),
          };
        }
        if (compact.startsWith("WITH keyword_input AS")) {
          keywordBatchQueries += 1;
          const keywords = JSON.parse(values[0]);
          return {
            rows: keywords.map((keyword, index) => ({
              identity_key: keyword.identity_key,
              keyword_id: String(index + 3000),
            })),
          };
        }
        if (compact.startsWith("WITH institution_input AS MATERIALIZED")) {
          institutionBatchQueries += 1;
          hierarchySql.push(compact);
          const institutions = JSON.parse(values[0]);
          return {
            rows: institutions.map((institution, index) => ({
              identity_key: institution.identity_key,
              institution_id: String(7000 + index),
            })),
          };
        }
        if (compact.startsWith("WITH journal_input AS MATERIALIZED")) {
          journalBatchQueries += 1;
          hierarchySql.push(compact);
          const journals = JSON.parse(values[0]);
          if (compact.includes("journal_updated AS")) {
            return {
              rows: [{ updated: 1, inserted: 0, issns_linked: 2 }],
            };
          }
          return {
            rows: journals.map((journal) => ({
              identity_key: journal.identity_key,
              journal_id: "4000",
            })),
          };
        }
        if (compact.startsWith("WITH volume_input AS MATERIALIZED")) {
          volumeBatchQueries += 1;
          hierarchySql.push(compact);
          const volumes = JSON.parse(values[0]);
          return {
            rows: volumes.map((volume) => ({
              identity_key: volume.identity_key,
              volume_id: "5000",
            })),
          };
        }
        if (compact.startsWith("WITH issue_input AS MATERIALIZED")) {
          issueBatchQueries += 1;
          hierarchySql.push(compact);
          const issues = JSON.parse(values[0]);
          resolvedIssueNumbers.push(
            ...issues.map((issue) => issue.issue_number),
          );
          return {
            rows: issues.map((issue) => ({
              identity_key: issue.identity_key,
              issue_id: "6000",
            })),
          };
        }
        if (compact.startsWith("WITH article_input AS MATERIALIZED")) {
          bulkArticleSql.push(compact);
          const input = JSON.parse(values[0]);
          persistedIssueIds.push(
            ...input.map((article) => article.issue_id),
          );
          persistedInstitutionIds.push(
            ...input.flatMap((article) =>
              article.authors.flatMap(
                (author) => author.institution_ids || [],
              ),
            ),
          );
          return {
            rows: input.map((article) => ({
              scan_index: article.scan_index,
              article_id: String(article.scan_index + 1),
              created: true,
              primary_topic: article.primary_topic_id,
              issue_id: article.issue_id,
              topics_linked: article.sub_topic_ids.length,
              keywords_linked: article.keywords.length,
            })),
          };
        }
        if (compact.startsWith("WITH article_updated AS")) {
          perArticleSql.push(compact);
          const articleIndex = Number(
            String(values[4]).split("/").at(-1),
          );
          return {
            rows: [
              {
                article_id: String(articleIndex + 1),
                created: true,
                primary_topic: null,
                topics_linked: 0,
                keywords_linked: 0,
              },
            ],
          };
        }
        if (compact.startsWith("WITH linked_articles AS MATERIALIZED")) {
          authorPageSql = compact;
          return {
            rows: storedArticles.slice(0, Number(values[1])).map(
              (article) => ({
                ...article,
                total_count: storedArticles.length,
              }),
            ),
          };
        }
        if (
          compact.startsWith('SELECT * FROM "Author" WHERE author_id')
        ) {
          return { rows: [targetAuthor] };
        }
        return { rows: [] };
      },
      release: () => {},
    };
    const articles = Array.from({ length: 100 }, (_, index) => ({
      title: `Article ${index}`,
      publication_year: 2024 + (index % 2),
      doi: `10.1000/${index}`,
      authors: [
        {
          display_name: "Target author",
          orcid: "https://orcid.org/0000-0002-1825-0097",
          institutions: [
            {
              openalex_id: "https://openalex.org/I100",
              display_name: "Institution One",
              country_code: "VN",
              type: "education",
            },
            {
              openalex_id: "I200",
              display_name: "Institution Two",
              country_code: "US",
              type: "facility",
            },
          ],
        },
      ],
      primary_topic: {
        display_name: "Shared primary topic",
        score: 0.95,
      },
      topics: [
        { display_name: "Shared sub topic", score: 0.8 },
      ],
      keywords: [
        { display_name: "Shared keyword", score: 0.7 },
      ],
      journal: {
        source_id: "https://openalex.org/S123",
        display_name: "Shared Journal",
        issn_l: "1234-567X",
        issns: ["1234-567X", "8765-4321"],
        type: "journal",
        is_open_access: true,
      },
      volume_number: "12",
      issue_number: "S1",
    }));

    const result = await persistOrcidScan(
      {
        targetAuthor: {
          display_name: "Target author",
          orcid: "https://orcid.org/0000-0002-1825-0097",
        },
        articles,
      },
      { databasePool: { connect: async () => client } },
    );

    assert.equal(result.summary.created, 100);
    assert.equal(result.articles.length, 20);
    assert.equal(result.article_total, 120);
    assert.match(
      authorPageSql,
      /aa\.author_id = \$1 AND COALESCE\(a\.is_deleted, false\) = false/,
    );
    assert.match(
      authorPageSql,
      /ORDER BY publication_year DESC, article_id DESC/,
    );
    assert.match(
      authorPageSql,
      /LEFT JOIN "Issue" issue ON issue\.issue_id = a\.issue_id/,
    );
    assert.match(
      authorPageSql,
      /LEFT JOIN "Volume" volume ON volume\.volume_id = issue\.volume_id/,
    );
    assert.match(
      authorPageSql,
      /journal\.journal_id = volume\.journal_id/,
    );
    assert.equal(result.articles[0].journal_name, "Shared Journal");
    assert.doesNotMatch(
      authorPageSql,
      /SELECT a\.\*/,
      "scan response must use the same safe article subset as GET",
    );
    assert.equal(authorBatchQueries, 3);
    assert.equal(authorBatchSql.length, 3);
    assert.ok(
      authorBatchSql.every((sql) => !/\sOR\s/.test(sql)),
      "author batch SQL must not use OR predicates",
    );
    assert.equal(
      authorBatchSql.filter((sql) => sql.includes("UNION ALL")).length,
      2,
    );
    assert.equal(topicBatchQueries, 1);
    assert.equal(keywordBatchQueries, 1);
    assert.equal(journalBatchQueries, 2);
    assert.equal(volumeBatchQueries, 1);
    assert.equal(issueBatchQueries, 1);
    assert.equal(institutionBatchQueries, 1);
    assert.ok(
      persistedInstitutionIds.includes("7000") &&
        persistedInstitutionIds.includes("7001"),
    );
    assert.deepEqual(resolvedIssueNumbers, ["S1"]);
    assert.ok(persistedIssueIds.every((id) => id === "6000"));
    assert.ok(
      hierarchySql.some((sql) =>
        sql.includes(
          "publication_year = COALESCE( volume.publication_year, matched.publication_year )",
        ),
      ),
    );
    assert.ok(
      hierarchySql.some(
        (sql) =>
          sql.includes(
            "country_code = COALESCE( institution.country_code, input.country_code )",
          ) &&
          sql.includes(
            "type = COALESCE(institution.type, input.type)",
          ) &&
          !sql.includes("display_name ="),
      ),
      "existing Institution metadata must only fill nullable fields",
    );
    assert.ok(
      hierarchySql.some((sql) =>
        sql.includes(
          "publication_year = COALESCE( issue.publication_year, matched.publication_year )",
        ),
      ),
    );
    assert.equal(
      namedArticleQueries,
      0,
      "PgBouncer transaction pooling requires unnamed article queries",
    );
    assert.equal(bulkArticleSql.length, 4);
    assert.equal(perArticleSql.length, 0);
    assert.ok(
      bulkArticleSql.every(
        (sql) =>
          !sql.includes("author_input") &&
          !sql.includes("topic_input") &&
          !sql.includes("keyword_input") &&
          !sql.includes('UPDATE "Author"') &&
          !sql.includes('UPDATE "Topic"') &&
          !sql.includes('INSERT INTO "Keyword"') &&
          !sql.includes('UPDATE "Journal"') &&
          !sql.includes('INSERT INTO "Volume"') &&
          !sql.includes('INSERT INTO "Issue"'),
      ),
      "bulk article SQL must only persist Article and resolved links",
    );
    assert.ok(
      bulkArticleSql.every(
        (sql) =>
          sql.includes('INSERT INTO "Institution_Author"') &&
          sql.includes("article.publication_year") &&
          sql.includes("ON CONFLICT DO NOTHING"),
      ),
      "institution-author links must be per persisted article year and idempotent",
    );
    assert.ok(
      queryCount <= 35,
      `expected <= 35 DB round trips, received ${queryCount}`,
    );
  });

  test("uses unnamed article queries across repeated idempotent scans", async () => {
    let targetAuthor = null;
    const storedArticles = [];
    const observedQueryNames = [];

    const client = {
      query: async (query, fallbackValues = []) => {
        let sql = query;
        let values = fallbackValues;
        if (typeof query === "object") {
          observedQueryNames.push(query.name);
          sql = query.text;
          values = query.values || [];
        }
        const compact = sql.replace(/\s+/g, " ").trim();

        if (
          compact.includes('FROM "Author"') &&
          compact.includes("FOR UPDATE")
        ) {
          return { rows: targetAuthor ? [targetAuthor] : [] };
        }
        if (compact.startsWith('INSERT INTO "Author"')) {
          targetAuthor = {
            author_id: "1000",
            display_name: values[0],
            orcid: values[1],
            openalex_id: values[2],
            is_deleted: false,
          };
          return { rows: [targetAuthor] };
        }
        if (compact.startsWith('UPDATE "Author"')) {
          return { rows: [targetAuthor] };
        }
        if (
          compact.includes('FROM "Article" a') &&
          compact.includes("FOR UPDATE OF a")
        ) {
          return {
            rows: storedArticles.map((article) => ({
              ...article,
              sub_topic_count: 0,
              keyword_count: 0,
            })),
          };
        }
        if (compact.startsWith("WITH author_input AS")) {
          return {
            rows: JSON.parse(values[0]).map((author) => ({
              identity_key: author.identity_key,
              author_id: targetAuthor.author_id,
              is_deleted: false,
            })),
          };
        }
        if (compact.startsWith("WITH matched_input AS")) {
          return { rows: [{ updated: 1, inserted: 0 }] };
        }
        if (compact.startsWith("WITH article_input AS MATERIALIZED")) {
          const inputArticles = JSON.parse(values[0]);
          return {
            rows: inputArticles.map((inputArticle) => {
              const created = inputArticle.existing_id == null;
              let storedArticle = storedArticles.find(
                (article) => article.doi === inputArticle.doi,
              );
              if (!storedArticle) {
                storedArticle = {
                  article_id: String(2000 + inputArticle.scan_index),
                  title: inputArticle.title,
                  publication_year: inputArticle.publication_year,
                  doi: inputArticle.doi,
                  is_deleted: false,
                  primary_topic: null,
                };
                storedArticles.push(storedArticle);
              }
              return {
                scan_index: inputArticle.scan_index,
                article_id: storedArticle.article_id,
                created,
                primary_topic: null,
                topics_linked: 0,
                keywords_linked: 0,
              };
            }),
          };
        }
        if (compact.startsWith("WITH linked_articles AS MATERIALIZED")) {
          return {
            rows: storedArticles.map((article) => ({
              ...article,
              total_count: storedArticles.length,
            })),
          };
        }
        if (
          compact.startsWith('SELECT * FROM "Author" WHERE author_id')
        ) {
          return { rows: [targetAuthor] };
        }
        return { rows: [] };
      },
      release: () => {},
    };
    const databasePool = { connect: async () => client };
    const input = {
      targetAuthor: {
        display_name: "Target author",
        orcid: "https://orcid.org/0000-0002-1825-0097",
      },
      articles: [
        {
          title: "Repeated article one",
          publication_year: 2025,
          doi: "10.1000/repeated-1",
          authors: [],
          topics: [],
          keywords: [],
        },
        {
          title: "Repeated article two",
          publication_year: 2024,
          doi: "10.1000/repeated-2",
          authors: [],
          topics: [],
          keywords: [],
        },
      ],
    };

    const first = await persistOrcidScan(input, { databasePool });
    const second = await persistOrcidScan(input, { databasePool });

    assert.equal(first.summary.created, 2);
    assert.equal(second.summary.created, 0);
    assert.equal(second.summary.already_existed, 2);
    assert.deepEqual(
      observedQueryNames,
      [undefined, undefined],
      "article persistence must not register named prepared statements",
    );
  });
});
