import pool from '../src/config/database.js';

async function main() {
  const client = await pool.connect();
  try {
    console.log('Bắt đầu thiết lập cơ sở dữ liệu cho Project...');

    await client.query('BEGIN');

    // 1. Xóa các bảng cũ nếu tồn tại
    console.log('- Đang xóa các bảng cũ nếu có...');
    await client.query('DROP TABLE IF EXISTS "Project_Journal" CASCADE;');
    await client.query('DROP TABLE IF EXISTS "Subject_Category_Project" CASCADE;');
    await client.query('DROP TABLE IF EXISTS "Project" CASCADE;');
    await client.query('DROP TABLE IF EXISTS "project_journal" CASCADE;');
    await client.query('DROP TABLE IF EXISTS "project_subject_category" CASCADE;');
    await client.query('DROP TABLE IF EXISTS "project" CASCADE;');

    // 2. Tạo bảng Project mới với BIGINT tự sinh (IDENTITY)
    console.log('- Đang tạo bảng "Project"...');
    await client.query(`
      CREATE TABLE "Project" (
        "project_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" UUID NOT NULL REFERENCES "user"("user_id") ON DELETE CASCADE,
        "title" VARCHAR(255) NOT NULL,
        "subject_area" BIGINT REFERENCES "Subject_Area"("subject_area_id") ON DELETE SET NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);

    // 3. Tạo bảng trung gian Subject_Category_Project
    console.log('- Đang tạo bảng trung gian "Subject_Category_Project"...');
    await client.query(`
      CREATE TABLE "Subject_Category_Project" (
        "project_id" BIGINT NOT NULL REFERENCES "Project"("project_id") ON DELETE CASCADE,
        "subject_category_id" BIGINT NOT NULL REFERENCES "Subject_Category"("subject_category_id") ON DELETE CASCADE,
        PRIMARY KEY ("project_id", "subject_category_id")
      );
    `);

    // 4. Tạo bảng trung gian Project_Journal
    console.log('- Đang tạo bảng trung gian "Project_Journal"...');
    await client.query(`
      CREATE TABLE "Project_Journal" (
        "project_id" BIGINT NOT NULL REFERENCES "Project"("project_id") ON DELETE CASCADE,
        "journal_id" BIGINT NOT NULL REFERENCES "Journal"("journal_id") ON DELETE CASCADE,
        PRIMARY KEY ("project_id", "journal_id")
      );
    `);

    await client.query('COMMIT');
    console.log('Thiết lập cơ sở dữ liệu Project THÀNH CÔNG!');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Lỗi khi thiết lập cơ sở dữ liệu Project:', err);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
