import pool from '../src/config/database.js';

async function main() {
  const client = await pool.connect();
  try {
    console.log('Bắt đầu thiết lập cơ sở dữ liệu cho Comment & Bookmark...');

    await client.query('BEGIN');

    console.log('- Đang tạo bảng "Comment"...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS "Comment" (
        "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "article_id" BIGINT NOT NULL REFERENCES "Article"("article_id") ON DELETE CASCADE,
        "user_id" UUID NOT NULL REFERENCES "user"("user_id") ON DELETE CASCADE,
        "content" TEXT NOT NULL,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
      );
    `);
    await client.query(`
      CREATE INDEX IF NOT EXISTS "idx_comment_article_id" ON "Comment"("article_id");
    `);

    console.log('- Đang tạo bảng "Bookmark"...');
    await client.query(`
      CREATE TABLE IF NOT EXISTS "Bookmark" (
        "bookmark_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        "user_id" UUID NOT NULL REFERENCES "user"("user_id") ON DELETE CASCADE,
        "article_id" BIGINT NOT NULL REFERENCES "Article"("article_id") ON DELETE CASCADE,
        "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        UNIQUE ("user_id", "article_id")
      );
    `);
    await client.query(`
      CREATE INDEX IF NOT EXISTS "idx_bookmark_user_id" ON "Bookmark"("user_id");
    `);

    await client.query('COMMIT');
    console.log('Thiết lập cơ sở dữ liệu Comment & Bookmark THÀNH CÔNG!');
  } catch (err) {
    await client.query('ROLLBACK');
    console.error('Lỗi khi thiết lập cơ sở dữ liệu Comment & Bookmark:', err);
  } finally {
    client.release();
    await pool.end();
  }
}

main();
