-- 0001_create_comment_bookmark_tables.sql
-- Tạo bảng "Comment" và "Bookmark" phục vụ API bình luận & lưu bài báo.
-- Chạy thủ công qua psql hoặc `node scripts/setup_comment_bookmark_db.js` (tương đương).

CREATE TABLE IF NOT EXISTS "Comment" (
  "comment_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "article_id" BIGINT NOT NULL REFERENCES "Article"("article_id") ON DELETE CASCADE,
  "user_id" UUID NOT NULL REFERENCES "user"("user_id") ON DELETE CASCADE,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS "idx_comment_article_id" ON "Comment"("article_id");

CREATE TABLE IF NOT EXISTS "Bookmark" (
  "bookmark_id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" UUID NOT NULL REFERENCES "user"("user_id") ON DELETE CASCADE,
  "article_id" BIGINT NOT NULL REFERENCES "Article"("article_id") ON DELETE CASCADE,
  "created_at" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE ("user_id", "article_id")
);

CREATE INDEX IF NOT EXISTS "idx_bookmark_user_id" ON "Bookmark"("user_id");
