-- 0006_create_orcid_scan_job_items.sql
CREATE TABLE IF NOT EXISTS public."Orcid_Scan_Job_Item" (
  item_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  job_id uuid NOT NULL REFERENCES public."Orcid_Scan_Job"(job_id) ON DELETE CASCADE,
  article_id bigint NOT NULL REFERENCES public."Article"(article_id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT "uq_orcid_scan_job_item" UNIQUE (job_id, article_id)
);

CREATE INDEX IF NOT EXISTS "idx_orcid_scan_job_items_job_item"
  ON public."Orcid_Scan_Job_Item" (job_id, item_id);

ALTER TABLE public."Orcid_Scan_Job_Item" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."Orcid_Scan_Job_Item" FROM PUBLIC;
